[tool.deptry.package_module_name_map]
python-dotenv = "dotenv"
SPARQLWrapper = "SPARQLWrapper"
google-generativeai = ["google.generativeai", "google"]
neo4j="neo4j"
ollama="ollama"
selenium="selenium"